### ISSUE TITLE
Needs for a way to view console and developer tools output

### ISSUE THREAD

**Issue by sage-godspeed** [Akumzy/mobi#2]
I will need to switch tabs on my browser to view and inspect things using my developer tools. Hoping for a new update to be able to streamline this process. into a single tab

**Comment by Akumzy** [comment]
Sorry for late response I didn't know why Github didn't notify me.

Anyway @sage-godspeed I will see what I can do about that

**Comment by sage-godspeed** [comment]
no wahala chief

I finally found my way around the inspect elements part, just did some more digging, haven't done anything with the console just yet. 
I think a how-to-use modal will be helpful for people
Cheers

**Comment by Akumzy** [comment]
Yeah about that you can easily right click on the view to inspect
